// This file contains sample meanings for Arabic words
// In production, this file would be generated by integrate_meanings.py

const WORD_MEANINGS = {
  // Words from Surah Al-Ikhlas
  'قُلْ': [
    'Say (imperative)',
    'Tell',
    'Command to speak',
    'Proclaim',
    'Declare'
  ],
  'هُوَ': [
    'He',
    'It (masculine)',
    'That one',
    'Him'
  ],
  'اللَّهُ': [
    'Allah',
    'God',
    'The One True God',
    'The Creator',
    'The Sustainer'
  ],
  'أَحَدٌ': [
    'One',
    'Single',
    'Unique',
    'Indivisible',
    'Sole'
  ],
  'الصَّمَدُ': [
    'The Eternal',
    'The Absolute',
    'The Self-Sufficient',
    'The One on whom all depend',
    'The One who needs none but all need Him'
  ],
  'لَمْ': [
    'Not (past negation)',
    'Did not',
    'Has not'
  ],
  'يَلِدْ': [
    'Beget',
    'Give birth to',
    'Father',
    'Generate',
    'Produce offspring'
  ],
  'وَلَمْ': [
    'And not',
    'Nor',
    'And did not'
  ],
  'يُولَدْ': [
    'Be born',
    'Be begotten',
    'Come into existence',
    'Be produced'
  ],
  'وَلَمْ يَكُن': [
    'And there is not',
    'And there has never been',
    'And there does not exist'
  ],
  'لَّهُ': [
    'For Him',
    'To Him',
    'His'
  ],
  'كُفُوًا': [
    'Equal',
    'Equivalent',
    'Comparable',
    'Like',
    'Peer'
  ],

  // Words from Surah Al-Inshiqaq
  'إِذَا': [
    'When',
    'If',
    'Whenever',
    'At the time',
    'As soon as'
  ],
  'السَّمَاءُ': [
    'The sky',
    'The heaven',
    'The firmament',
    'The celestial sphere',
    'The atmosphere'
  ],
  'انشَقَّتْ': [
    'Split',
    'Torn apart',
    'Rent asunder',
    'Cracked open',
    'Cleaved'
  ],
  'وَأَذِنَتْ': [
    'And has listened',
    'And has hearkened',
    'And has given ear',
    'And has obeyed',
    'And has responded'
  ],
  'أَذِنَتْ': [
    'Listens',
    'Hearkens',
    'Gives ear',
    'Obeys',
    'Responds'
  ],
  'لِرَبِّهَا': [
    'To its Lord',
    'For its Lord',
    'To its Master',
    'For its Sustainer',
    'To its Creator'
  ],
  'وَحُقَّتْ': [
    'And it must',
    'And it is right',
    'And it is fitting',
    'And it is duty-bound',
    'And it is obligated'
  ],
  'حُقَّتْ': [
    'It must do so',
    'It is right',
    'It is fitting',
    'It is duty-bound',
    'It is obligated'
  ],
  'وَإِذَا': [
    'And when',
    'And if',
    'And whenever',
    'And at the time',
    'And as soon as'
  ],
  'الْأَرْضُ': [
    'The earth',
    'The ground',
    'The land',
    'The soil',
    'The world'
  ],
  'مُدَّتْ': [
    'Is spread out',
    'Is stretched',
    'Is extended',
    'Is flattened',
    'Is expanded'
  ],
  'وَأَلْقَتْ': [
    'And has cast out',
    'And has thrown out',
    'And has ejected',
    'And has expelled',
    'And has discharged'
  ],
  'مَا': [
    'What',
    'That which',
    'Whatever',
    'Something',
    'Anything'
  ],
  'مَا فِيهَا': [
    'That within it',
    'What is in it',
    'Whatever is in it',
    'Its contents',
    'All that it contains'
  ],
  'فِيهَا': [
    'In it',
    'Within it',
    'Inside it',
    'Therein',
    'Contained in it'
  ],
  'وَتَخَلَّتْ': [
    'And becomes empty',
    'And is void',
    'And is vacant',
    'And is cleared',
    'And is abandoned'
  ],
  'تَخَلَّتْ': [
    'Casts out',
    'Becomes empty',
    'Is void',
    'Is vacant',
    'Is cleared'
  ],

  // Words from Surah Al-Ghashiyah (The Overwhelming)
  'هَلْ': [
    'Has',
    'Did',
    'Whether',
    'Is it',
    'Is there'
  ],
  'أَتَاكَ': [
    'Reached you',
    'Come to you',
    'Arrived to you',
    'Been conveyed to you',
    'Been brought to you'
  ],
  'حَدِيثُ': [
    'Report',
    'Story',
    'Narration',
    'Account',
    'News'
  ],
  'الْغَاشِيَةِ': [
    'The Overwhelming',
    'The Enveloping',
    'The Covering',
    'The Day of Judgment',
    'The Calamity'
  ],
  'وُجُوهٌ': [
    'Faces',
    'Countenances',
    'Visages',
    'Expressions',
    'Appearances'
  ],
  'يَوْمَئِذٍ': [
    'That Day',
    'On that Day',
    'At that time',
    'Then',
    'At that moment'
  ],
  'خَاشِعَةٌ': [
    'Humbled',
    'Downcast',
    'Submissive',
    'Humble',
    'Lowly'
  ],
  'عَامِلَةٌ': [
    'Working',
    'Laboring',
    'Toiling',
    'Striving',
    'Exerting'
  ],
  'نَّاصِبَةٌ': [
    'Exhausted',
    'Weary',
    'Tired',
    'Fatigued',
    'Worn out'
  ],
  'تَصْلَىٰ': [
    'Will burn',
    'Will enter',
    'Will be exposed to',
    'Will endure',
    'Will suffer'
  ],
  'نَارًا': [
    'Fire',
    'Hellfire',
    'Flame',
    'Blaze',
    'Inferno'
  ],
  'حَامِيَةً': [
    'Intensely hot',
    'Scorching',
    'Burning',
    'Blazing',
    'Fiercely hot'
  ],
  'تُسْقَىٰ': [
    'Given to drink',
    'Made to drink',
    'Offered to drink',
    'Provided with drink',
    'Supplied with drink'
  ],
  'مِنْ': [
    'From',
    'Of',
    'Out of',
    'Among',
    'By'
  ],
  'عَيْنٍ': [
    'Spring',
    'Fountain',
    'Source',
    'Well',
    'Eye'
  ],
  'آنِيَةٍ': [
    'Boiling',
    'Scalding',
    'Extremely hot',
    'Burning hot',
    'Seething'
  ],
  'ضَرِيعٍ': [
    'Thorny plant',
    'Bitter herb',
    'Dry thorns',
    'Poisonous plant',
    'Bitter food'
  ],
  'نَاصِبَةٌ': [
    'Laboring',
    'Toiling',
    'Striving',
    'Working hard',
    'Exerting'
  ]
};

// Make the word meanings available globally
if (typeof window !== 'undefined') {
  window.WORD_MEANINGS = WORD_MEANINGS;
}
