// This file contains sample meanings for Arabic words
// In production, this file would be generated by integrate_meanings.py

const WORD_MEANINGS = {
  'قُلْ': [
    'Say (imperative)',
    'Tell',
    'Command to speak',
    'Proclaim',
    'Declare'
  ],
  'هُوَ': [
    'He',
    'It (masculine)',
    'That one',
    'Him'
  ],
  'اللَّهُ': [
    'Allah',
    'God',
    'The One True God',
    'The Creator',
    'The Sustainer'
  ],
  'أَحَدٌ': [
    'One',
    'Single',
    'Unique',
    'Indivisible',
    'Sole'
  ],
  'الصَّمَدُ': [
    'The Eternal',
    'The Absolute',
    'The Self-Sufficient',
    'The One on whom all depend',
    'The One who needs none but all need Him'
  ],
  'لَمْ': [
    'Not (past negation)',
    'Did not',
    'Has not'
  ],
  'يَلِدْ': [
    'Beget',
    'Give birth to',
    'Father',
    'Generate',
    'Produce offspring'
  ],
  'وَلَمْ': [
    'And not',
    'Nor',
    'And did not'
  ],
  'يُولَدْ': [
    'Be born',
    'Be begotten',
    'Come into existence',
    'Be produced'
  ],
  'وَلَمْ يَكُن': [
    'And there is not',
    'And there has never been',
    'And there does not exist'
  ],
  'لَّهُ': [
    'For Him',
    'To Him',
    'His'
  ],
  'كُفُوًا': [
    'Equal',
    'Equivalent',
    'Comparable',
    'Like',
    'Peer'
  ]
};

// Make the word meanings available globally
if (typeof window !== 'undefined') {
  window.WORD_MEANINGS = WORD_MEANINGS;
}
